query Cart($country: CountryCode = SE, $id: ID!) @inContext(country: $country) {
	cart(id: $id) {
		...CartFragment
	}
}

mutation CreateCart($country: CountryCode = SE, $cartInput: CartInput)
@inContext(country: $country) {
	cartCreate(input: $cartInput) {
		cart {
			...CartFragment
		}
		userErrors {
			...CartErrorsFragment
		}
	}
}

mutation CartBuyerIdentityUpdate($cartId: ID!, $buyerIdentity: CartBuyerIdentityInput!) {
	cartBuyerIdentityUpdate(cartId: $cartId, buyerIdentity: $buyerIdentity) {
		cart {
			...CartFragment
		}
		userErrors {
			...CartErrorsFragment
		}
	}
}

mutation AddItemToCart($country: CountryCode = SE, $cartId: ID!, $lines: [CartLineInput!]!)
@inContext(country: $country) {
	cartLinesAdd(cartId: $cartId, lines: $lines) {
		cart {
			...CartFragment
		}
		userErrors {
			...CartErrorsFragment
		}
	}
}

mutation RemoveItemFromCart($cartId: ID!, $lineIds: [ID!]!) {
	cartLinesRemove(cartId: $cartId, lineIds: $lineIds) {
		cart {
			...CartFragment
		}
		userErrors {
			...CartErrorsFragment
		}
	}
}

mutation UpdateItemFromCart(
	$country: CountryCode = SE
	$cartId: ID!
	$lines: [CartLineUpdateInput!]!
) @inContext(country: $country) {
	cartLinesUpdate(cartId: $cartId, lines: $lines) {
		cart {
			...CartFragment
		}
		userErrors {
			...CartErrorsFragment
		}
	}
}
