query AllShopifyCollections($country: CountryCode = US, $first: Int = 5)
@inContext(country: $country) {
	collections(first: $first) {
		edges {
			node {
				...CollectionFragment
			}
		}
		pageInfo {
			hasNextPage
		}
	}
}

query ShopifyCollection($country: CountryCode = US, $handle: String, $first: Int = 10)
@inContext(country: $country) {
	collection(handle: $handle) {
		id
		handle
		title
		description
		image {
			id
			url
			height
			width
			altText
		}
		products(first: $first) {
			edges {
				node {
					...ProductFragment
				}
			}
		}
	}
}
