query AllShopifyProducts($country: CountryCode = SE, $first: Int = 100)
@inContext(country: $country) {
	products(first: $first, query: "available_for_sale") {
		edges {
			node {
				...ProductFragment
			}
		}
		pageInfo {
			hasNextPage
		}
	}
}

query ShopifyProduct($country: CountryCode = SE, $handle: String) @inContext(country: $country) {
	product(handle: $handle) {
		...ProductFragment
	}
}

query ShopifyVariant($country: CountryCode = SE, $id: ID!) @inContext(country: $country) {
	variant: node(id: $id) {
		... on ProductVariant {
			id
			title
			weight
			availableForSale
			selectedOptions {
				name
				value
			}
			price {
				amount
				currencyCode
			}
			product {
				...ProductFragment
			}
		}
	}
}
