fragment ProductFragment on Product {
	id
	handle
	title
	description
	featuredImage {
		id
		url
		height
		width
		altText
	}
	options {
		id
		name
		values
	}
	variants(first: 10) {
		edges {
			node {
				id
				title
				weight
				availableForSale
				selectedOptions {
					name
					value
				}
				image {
					id
					url(transform: { maxWidth: 400, maxHeight: 400, crop: CENTER })
					height
					width
					altText
				}
				price {
					amount
					currencyCode
				}
			}
		}
	}
}
