fragment ImageCartThumbnailFragment on FileFieldInterface {
	format
	id
	mimeType
	url
	title
	responsiveImage(imgixParams: { ar: "4:4", fit: clamp, w: 200, h: 200 }) {
		...ResponsiveImageFragment
	}
}
