fragment MediaPortraitFragment on FileField {
	id
	alt
	basename
	format
	mimeType
	size
	title
	url
	width
	height
	responsiveImage(imgixParams: { ar: "1:2", auto: format, fit: crop, crop: focalpoint }) {
		...ResponsiveImageFragment
	}
	video {
		thumbnailUrl
		streamingUrl
		mp4Url(res: high)
		mp4high: mp4Url(res: high)
		mp4med: mp4Url(res: medium)
		mp4low: mp4Url(res: low)
		framerate
		duration
	}
}
