query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		id
		title
		slug
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

fragment AboutFragment on AboutRecord {
	id
	title
	slug
	sections {
		__typename
		... on AboutTwoColumnBlockRecord {
			id
			media {
				...ImageFragment
			}
			text {
				blocks
				links
				value
			}
		}
		... on AboutTextBlockRecord {
			id
			text {
				blocks
				links
				value
			}
		}
		... on FullscreenBlockRecord {
			id
			media {
				...MediaFragment
			}
		}
	}

	content {
		blocks
		links
		value
	}
}
