query AllAbouts($first: IntType = 100, $skip: IntType = 0) {
	allAbouts(first: $first, skip: $skip) {
		...AboutLightFragment
	}
	_allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

fragment AboutLightFragment on AboutRecord {
	id
	title
	slug
	image {
		...ImageThumbnailFragment
	}
}

fragment AboutFragment on AboutRecord {
	id
	title
	slug
	image {
		...ImageFragment
	}
	sections {
		__typename
		... on AboutTwoColumnBlockRecord {
			id
			media {
				...ImageFragment
			}
			text {
				blocks {
					__typename
					... on ContactFormBlockRecord {
						id
						message
					}
					... on TwoColumnBlockRecord {
						id
						text
					}
				}
				links
				value
			}
		}
		... on AboutThreeColumnBlockRecord {
			id
			c1Media {
				...MediaFragment
			}
			c1Text {
				links
				value
				blocks
			}
			c2Media {
				...MediaFragment
			}
			c2Text {
				links
				value
				blocks
			}
			c3Media {
				...MediaFragment
			}
			c3Text {
				links
				value
				blocks
			}
		}
		... on AboutTextBlockRecord {
			id
			text {
				links
				value
			}
			layout
		}
		... on FullscreenBlockRecord {
			id
			media {
				...MediaFragment
			}
		}
	}
	content {
		blocks
		links
		value
	}
}
