query AllCollections($first: IntType = 100, $skip: IntType = 0) {
	allCollections(first: $first, skip: $skip) {
		...CollectionFragment
	}
	_allCollectionsMeta {
		count
	}
}

query Collection($slug: String) {
	collection(filter: { slug: { eq: $slug } }) {
		...CollectionFragment
	}
}

fragment CollectionFragment on CollectionRecord {
	id
	title
	titlePlural
	slug
	position
	_allReferencingProducts(first: 100) {
		...ProductLightFragment
	}
}

query AllShopifyCollections($first: IntType = 100, $skip: IntType = 0) {
	allShopifyCollections(first: $first, skip: $skip) {
		...ShopifyCollectionFragment
	}
	_allShopifyCollectionsMeta {
		count
	}
}

query ShopifyCollection($handle: String) {
	shopifyCollection(filter: { handle: { eq: $handle } }) {
		...ShopifyCollectionFragment
	}
}

fragment ShopifyCollectionFragment on ShopifyCollectionRecord {
	id
	title
	handle
	shopifyId
	products {
		...ShopifyProductFragment
	}
}
