query Menu($first: IntType = 100, $skip: IntType = 0) {
	allCollections(first: $first, skip: $skip) {
		id
		title
		image: menuImage {
			...ImageSquareFragment
		}
		slug
	}
	_allCollectionsMeta {
		count
	}

	allAbouts(first: $first, skip: $skip) {
		id
		title
		slug
		image {
			...ImageSquareFragment
		}
	}
	_allAboutsMeta {
		count
	}

	allFaqSections(first: $first, skip: $skip) {
		id
		title
		slug
		inMenu
		image {
			...ImageSquareFragment
		}
	}
	_allFaqSectionsMeta {
		count
	}
	allLegals(first: $first, skip: $skip) {
		id
		title
		slug
	}
	_allLegalsMeta {
		count
	}
	general {
		instagram
		facebook
		twitter
	}
	contact {
		title
		slug
		image {
			...ImageSquareFragment
		}
	}
}
