query Menu($first: IntType = 100, $skip: IntType = 0) {
	allCollections(first: $first, skip: $skip) {
		id
		title
		slug
	}
	_allCollectionsMeta {
		count
	}
	allFaqSections(first: $first, skip: $skip) {
		id
		title
		slug
	}
	_allFaqSectionsMeta {
		count
	}
}
