query AllProducts($first: IntType = 100, $skip: IntType = 0) {
	allProducts(first: $first, skip: $skip) {
		...ProductLightFragment
	}
	_allProductsMeta {
		count
	}
}

query Product($slug: String) {
	product(filter: { slug: { eq: $slug } }) {
		...ProductFragment
	}
}

fragment ProductLightFragment on ProductRecord {
	id
	shopifyId
	title
	slug
	image {
		...ImageFragment
	}
	shopifyData
}

fragment ProductFragment on ProductRecord {
	id
	shopifyId
	title
	description {
		blocks
		value
		links
	}
	shortSummary {
		blocks
		value
		links
	}
	description {
		blocks
		value
		links
	}
	slug
	image {
		...ImageFragment
	}
	shopifyData
}
