query AllProducts($first: IntType = 100, $skip: IntType = 0) {
	allProducts(first: $first, skip: $skip) {
		...ProductLightFragment
	}
	_allProductsMeta {
		count
	}
}

query Product($slug: String) {
	product(filter: { slug: { eq: $slug } }) {
		...ProductFragment
	}
}

query AllProductByCollection($collectionId: ItemId, $first: IntType = 100, $skip: IntType = 0) {
	allProducts(first: $first, skip: $skip, filter: { collection: { eq: $collectionId } }) {
		...ProductLightFragment
	}
	_allProductsMeta(filter: { collection: { eq: $collectionId } }) {
		count
	}
}

query AllCartProducts($shopifyIds: [String]!, $first: IntType = 100, $skip: IntType = 0) {
	allProducts(first: $first, skip: $skip, filter: { shopifyId: { in: $shopifyIds } }) {
		id
		shopifyId
		image {
			...ImageCartThumbnailFragment
		}
	}
	_allProductsMeta(filter: { shopifyId: { in: $shopifyIds } }) {
		count
	}
}

fragment ProductLightFragment on ProductRecord {
	id
	shopifyId
	title
	slug
	collection {
		id
		title
		slug
	}
	image {
		...ImageThumnbailFragment
	}
	imageSecondary {
		...ImageThumnbailFragment
	}
	usp {
		id
		title
		description
	}
	shopifyData
}

fragment ProductFragment on ProductRecord {
	id
	shopifyId
	title
	collection {
		id
		title
		slug
	}
	description {
		blocks
		value
		links
	}
	shortSummary {
		blocks
		value
		links
	}
	description {
		blocks
		value
		links
	}
	slug
	image {
		...ImageFragment
	}
	imageSecondary {
		...ImageFragment
	}
	usp {
		id
		title
		description
	}
	sections {
		... on ProductMediaBlockRecord {
			id
			text {
				blocks
				value
				links
			}
			productMedia {
				...ProductMediaItemFragment
			}
		}
	}
	options: _allReferencingProductVariantOptions(first: 100) {
		id
		name
		values
		shopifyId
	}
	variants: _allReferencingProductVariants(first: 100) {
		id
		title
		shopifyId
	}
}

fragment ProductMediaItemFragment on ProductMediaModelRecord {
	id
	title
	altText
	thumbnail {
		...ImageFragment
	}
	variation {
		id
		color {
			id
			title
		}
		media {
			...ImageFragment
		}
	}
}
