query Start {
	start {
		id
		sections {
			__typename
			... on FullscreenBlockRecord {
				id
				media {
					...MediaFragment
				}
				altMedia {
					...MediaFragment
				}
			}
			... on StartProductBlockRecord {
				id
				headline
				collection {
					id
					slug
					title
				}
				columns
				selectedProducts {
					product {
						...ProductLightFragment
					}
				}
			}

			... on StartEditorialBlockRecord {
				id
				headline
				text
				buttonText
				media {
					...MediaFragment
				}
				mediaOnTop {
					...MediaFragment
				}
				lottieAnimation {
					url
				}
				about {
					id
					slug
					title
				}
			}
		}
	}
}
