query Start {
	start {
		id
		sections {
			__typename
			... on FullscreenBlockRecord {
				id
				media {
					...MediaFragment
				}
				mediaMobile: media {
					...MediaPortraitFragment
				}
				altMedia {
					...MediaFragment
				}
				altMediaMobile: altMedia {
					...MediaPortraitFragment
				}
			}
			... on StartProductBlockRecord {
				id
				headline
				collection {
					id
					slug
					title
				}
				columns
				selectedProducts {
					id
					product {
						...ProductLightFragment
					}
					image {
						...ImageThumbnailFragment
					}
					imageSecondary {
						...ImageThumbnailFragment
					}
					color {
						id
						title
					}
				}
			}

			... on StartEditorialBlockRecord {
				id
				headline
				text
				buttonText
				media {
					...MediaFragment
				}
				mediaOnTop {
					...MediaFragment
				}
				lottieAnimation {
					url
				}
				about {
					id
					slug
					title
				}
			}
		}
		media {
			...MediaFragment
		}
		mediaMobile: media {
			...MediaPortraitFragment
		}
		altMedia {
			...MediaFragment
		}
		altMediaMobile: altMedia {
			...MediaPortraitFragment
		}
		blackLogo
	}
}
